---
# certs pv setup
apiVersion: v1
kind: PersistentVolume
metadata:
  name: certspv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/certspv
---
# ssldir claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppetca-cadir-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# cadir claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppetca-ssldir-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
