---
# psql pv setup
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psqlpv
  labels:
    type: local
spec:
  capacity:
    storage: 12Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/psqlpv
---
# psql claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psqlvolclaim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
