# postgresql setup
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app.kubernetes.io/name: psql
  ports:
  - protocol: TCP
    port: 5432
---
# psql init puppetdb
apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-init-puppetdb-config
data:
  # https://www.puppet.com/docs/puppetdb/8/configure_postgres
  initdb.sql: |
    create user puppetdb_read;
    grant puppetdb_read to puppetdb;
    revoke create on schema public from public;
    grant create on schema public to puppetdb;
    alter default privileges for user puppetdb in schema public grant select on tables to puppetdb_read;
    alter default privileges for user puppetdb in schema public grant usage on sequences to puppetdb_read;
    alter default privileges for user puppetdb in schema public grant execute on functions to puppetdb_read;
    grant select on all tables in schema public to puppetdb_read;
    grant usage on all sequences in schema public to puppetdb_read;
    grant execute on all functions in schema public to puppetdb_read;
    create extension pg_trgm;
---
# psql deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql
  labels:
    app.kubernetes.io/name: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: psql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: psql
    spec:
      volumes:
      - name: psql-storage
        persistentVolumeClaim:
          claimName: psqlvolclaim
      containers:
      - name: psql
        image: postgres
        env:
        - name: POSTGRES_USER
          value: puppetdb
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: puppetdb
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: psql-storage
          mountPath: /var/lib/postgresql
        volumeMounts:
          - name: psql-init-puppetdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: psql-init-puppetdb
          configMap:
            name: psql-init-puppetdb-config
