# setup puppetca with default config
---
# puppetca service
apiVersion: v1
kind: Service
metadata:
  name: puppetca
spec:
  selector:
    app.kubernetes.io/name: puppetca
  ports:
  - protocol: TCP
    port: 8140
  type: LoadBalancer
---
# puppetca init scripts configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: puppetca-docker-entrypoint-configmap
data:
  50-fix-puppetserver-params.sh: |
    #!/usr/bin/env bash
    # workaround for https://github.com/voxpupuli/container-puppetserver/issues/51
    /opt/puppetlabs/bin/puppet config set server "puppet.default.svc.cluster.local"
---
# puppetca deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetca
  labels:
    app.kubernetes.io/name: puppetca
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: puppetca
  template:
    metadata:
      labels:
        app.kubernetes.io/name: puppetca
    spec:
      containers:
      - name: puppetca
        image: ghcr.io/voxpupuli/container-puppetserver:8.4.0-latest
        env:
        - name: POD_METADATA_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CA_ENABLED
          value: 'true'
        - name: AUTOSIGN
          value: 'true'
        - name: CA_HOSTNAME
          value: puppetca.default.svc.cluster.local
        - name: CA_ALLOW_SUBJECT_ALT_NAMES
          value: 'true'
        - name: DNS_ALT_NAMES
          value: puppetca.default.svc.cluster.local
        - name: PUPPETSERVER_HOSTNAME
          value: "$(POD_METADATA_NAME).default.svc.cluster.local"
        - name: CSR_ATTRIBUTES
          value: '{"extension_requests": { "pp_apptier": "prd", "pp_role": "puppetca" } }'
        ports:
        - name: puppetca
          containerPort: 8140
        volumeMounts:
        - name: docker-entrypoint-configmap
          mountPath: /docker-custom-entrypoint.d
      volumes:
      - name: docker-entrypoint-configmap
        configMap:
          name: puppetca-docker-entrypoint-configmap
          defaultMode: 0500
