# setup puppetca with default config
---
# puppetca service
apiVersion: v1
kind: Service
metadata:
  name: puppetca
spec:
  selector:
    app.kubernetes.io/name: puppetca
  ports:
  - protocol: TCP
    port: 8140
  type: LoadBalancer
---
# puppetca deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetca
  labels:
    app.kubernetes.io/name: puppetca
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: puppetca
  template:
    metadata:
      labels:
        app.kubernetes.io/name: puppetca
    spec:
      containers:
      - name: puppetca
        image: ghcr.io/voxpupuli/container-puppetserver
        env:
        - name: DNS_ALT_NAMES
          value: puppetca,puppet
        - name: CA_ALLOW_SUBJECT_ALT_NAMES
          value: 'true'
        - name: PUPPETSERVER_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: puppetca
          containerPort: 8140
