---
# runner deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  labels:
    app.kubernetes.io/name: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: runner
    spec:
      volumes:
      - name: r10k-storage
        persistentVolumeClaim:
          claimName: r10kvolclaim
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ['/usr/bin/bash', '-c']
        args:
        - |
          sudo apt update
          sudo apt install -y ruby git
          sudo gem install r10k

          cat <<EOF>> r10k.yaml
          ---
          sources:
            control:
              remote: https://github.com/mdechiaro/puppet-control-repo
              basedir: /home/runner/code
          EOF

          r10k -c r10k.yaml deploy environment -mv

          ./config.sh --url https://github.com/mdechiaro/puppet-control-repo --unattended --token ${RUNNER_TOKEN}
          ./run.sh
        env:
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: runner-token
              key: RUNNER_TOKEN
        volumeMounts:
        - name: r10k-storage
          mountPath: /home/runner/code
