---
# puppetboard service http
apiVersion: v1
kind: Service
metadata:
  name: puppetboard
spec:
  selector:
    app.kubernetes.io/name: puppetboard
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
---
# puppetboard deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetboard
  labels:
    app.kubernetes.io/name: puppetboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: puppetboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: puppetboard
    spec:
      containers:
      - name: puppetboard
        image: ghcr.io/voxpupuli/puppetboard:5.3.0
        env:
        - name: PUPPETDB_HOST
          value: puppetdb.default.svc.cluster.local
        - name: PUPPETDB_PORT
          value: "8081"
        - name: PUPPETBOARD_PORT
          value: "8080"
        - name: PUPPETDB_KEY
          valueFrom:
            secretKeyRef:
              name: puppetboard-ssl-key
              key: PUPPETBOARD_SSL_KEY
        - name: PUPPETDB_CERT
          valueFrom:
            secretKeyRef:
              name: puppetboard-ssl-cert
              key: PUPPETBOARD_SSL_CERT
        - name: PUPPETDB_SSL_VERIFY
          valueFrom:
            secretKeyRef:
              name: puppetboard-ssl-ca-cert
              key: PUPPETBOARD_CA_CERT
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: puppetboard-secret-key
              key: PUPPETBOARD_SECRET_KEY
        - name: DEFAULT_ENVIRONMENT
          value: "*"
        ports:
        - name: puppetboard
          containerPort: 8080
